#!/usr/bin/env bash

join=$(tmux list-session | awk '{print $1}' | sed 's/://g' | fzf)

if [[ -z $join ]]; then
    exit 0
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $join
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $join
fi
