#!/bin/sh

SESSION_NAME=soa
PROJECT_PATH="$UNI/3q2/soa"
NOTES_PATH="$HOME/wiki/uni/soa"

tmux has-session -t $SESSION_NAME 2>/dev/null
if [ $? != 0 ]          # si no hay sesion se crea
then
    tmux new-session -s $SESSION_NAME -d
    tmux setenv ASIG=soa
    tmux send-keys -t $SESSION_NAME "export ASIG=soa" C-m
    tmux send-keys -t $SESSION_NAME "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME "cd zeos" C-m
    tmux send-keys -t $SESSION_NAME "nvim ." C-m
    tmux new-window -n ssh -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME:2 "ssh sistemes" C-m
    tmux send-keys -t $SESSION_NAME:2 "cd zeos" C-m
    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
