#!/bin/sh

HISTFILE="$XDG_CACHE_HOME/zsh/history"
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory

# already on the path
# export PATH="$HOME/.local/scripts":$PATH
# export PATH="$HOME/.local/scripts/statusbar":$PATH

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/scripts/tmux":$PATH
export MANPAGER='nvim +Man!'
#export MANWIDTH=999
# export PATH=$CARGO_HOME/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="$HOME/.local/share/cargo/bin":$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#        . "$HOME/.miniconda/etc/profile.d/conda.sh"
#    else
#        export PATH="$HOME/.miniconda/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<
