# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# window rules
# windowrule=isfloating:1,appid:pavucontrol
windowrule=isfloating:1,width:720,height:620,appid:pavucontrol
windowrule=isfloating:1,title:^floating*
windowrule=isfloating:1,appid:Nsxiv
# windowrule=tags:2,monitor:HDMI-A-1,title:firstterminal
windowrule=tags:9,monitor:DP-3,appid:discord
windowrule=tags:8,monitor:DP-3,appid:whatsapp-electron
