return {
  "rose-pine/neovim",
  -- "morhetz/gruvbox",
  "ellisonleao/gruvbox.nvim",
  "sainnhe/everforest",
  "wesgibbs/vim-irblack",
  "shaunsingh/nord.nvim",
  "gavinok/spaceway.vim",
  "ishan9299/modus-theme-vim",
  "rebelot/kanagawa.nvim",
  -- "Mofiqul/vscode.nvim",
  "folke/tokyonight.nvim",
  "xero/sourcerer.vim",
  "tomasiser/vim-code-dark",
  "navarasu/onedark.nvim",
  "tanvirtin/monokai.nvim",
  "dylanaraps/wal.vim",
  "phha/zenburn.nvim",
  "ishan9299/nvim-solarized-lua",
  "AlexvZyl/nordic.nvim",
  -- "eemed/sitruuna.vim",
  -- "xero/miasma.nvim",
  "savq/melange-nvim",
  "doums/darcula",
  "mcchrish/zenbones.nvim",
  "thimc/gruber-darker.nvim",
  "olivercederborg/poimandres.nvim",
  "NTBBloodbath/doom-one.nvim",
  "squarefrog/tomorrow-night.vim",
  "eemed/sitruuna.vim",
  "projekt0n/github-nvim-theme",
  -- "nyoom-engineering/oxocarbon.nvim",
  -- "mswift42/vim-themes"
  -- "maxmx03/solarized.nvim",
  -- "lifepillar/vim-solarized8",
}
