#!/bin/zsh

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export READER="zathura"

export UNI="$HOME/uni"
[ -e "$UNI/.env" ] && source "$UNI/.env"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export SUDO_ASKPASS="$HOME/.local/scripts/dmenupass"
export MANPAGER='nvim +Man!'

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/scripts":$PATH
export PATH="$HOME/.local/scripts/statusbar":$PATH

[ "$(tty)" = "/dev/tty1" ] && exec startx
