#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# export PATH="$PATH:${$(find ~/.local/scripts -type d -printf %p:)%%:}"
export PATH="$HOME/.local/scripts:$PATH"
export PATH="$HOME/.local/scripts/statusbar:$PATH"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/scripts/tmux":$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="$HOME/.local/share/cargo/bin":$PATH
export GOPATH="$HOME/.local/share/go"

unsetopt PROMPT_SP

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export READER="zathura"
export MENU="dmenu"
export SUDO_ASKPASS="$HOME/.local/scripts/dmenupass"
export MANPAGER='nvim +Man!'

export NOTES="$HOME/notes"
export UNI="$HOME/uni"
[ -e "$UNI/.env" ] && source "$UNI/.env"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

export GTK_THEME=Adwaita:dark

export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"

# export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export _JAVA_AWT_WM_NONREPARENTING=1

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
# export HISTFILE="${XDG_STATE_HOME}"/bash/history
export HISTFILE="$XDG_DATA_HOME/history"

# if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
# export MOZ_ENABLE_WAYLAND=1
# fi

# export QT_QPA_PLATFORMTHEME="gtk2" # Have QT use gtk2 theme.
# export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
# export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname

# [ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1

[ "$(tty)" = "/dev/tty1" ] && exec startx "$XINITRC"

# Switch escape and caps if tty and no passwd required:
# sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap 2>/dev/null
