#!/usr/bin/env bash

usage() {
    echo "Usage: $0 <input_file> <output_file>"
    echo "Example: $0 input.mp4 output.mp4"
    echo ""
    echo "Converts the input video file to H.264 video codec with AAC audio codec."
    echo "Options:"
    echo "  <input_file>   The path to the input video file"
    echo "  <output_file>  The path where the converted video will be saved"
    exit 1
}

if [ "$#" -ne 2 ]; then
    echo "Error: Missing arguments."
    usage
fi

input=$1
output=$2

ffmpeg -i "$input" -vcodec libx264 -crf 28 -preset veryslow \
    -acodec aac -b:a 128k "$output"
