#!/usr/bin/env bash

# This script is used to select an emacsclient frame to switch to.

# SESSIONS=$(echo "nix notes" | tr ' ' '\n')

CHOICE=$(dmenu -p "Select session: ")

notify-send "Selected $CHOICE"
emacsclient -c -s $CHOICE
if [ $? -eq 1 ]; then
    emacs --daemon=$CHOICE && notify-send "Starting emacs server for $CHOICE"
    emacsclient -c -s $CHOICE
fi

# if printf $SESSIONS | grep -qs $CHOICE; then
#     echo "Selected $CHOICE"
#     emacsclient -c -s $CHOICE
#     if [ $? -eq 1 ]; then
#         emacs --daemon=$CHOICE
#         emacsclient -c -s $CHOICE
#     fi
# else
#     echo "Invalid choice: $CHOICE"
#     exit 1
# fi

# case $CHOICE in
# 	nix)
#         emacsclient -c -s nix
#         if [ $? -eq 1 ]; then
#             emacs --daemon=nix
#             emacsclient -c -s nix
#         fi
#     ;;
# 	notes) ;;
#     *) exit 1 ;;
# esac
