#!/usr/bin/env bash

SETTINGS=/tmp/gammastep.current
PROGRAM_NAME=$0

LEVELS=(
    "6500 1.0"
    "5500 1.0"
    "5000 0.9"
    "4500 0.9"
    "4000 0.8"
    "3600 0.8"
    "3200 0.7"
    "3000 0.6"
    "3000 0.4"
    "2800 0.4"
)
MAX_LEVEL=$((${#LEVELS[@]} - 1))

usage () {
    echo "usage: $PROGRAM_NAME TEMP BRIGHTNESS"
    echo "       $PROGRAM_NAME --next"
    echo "       $PROGRAM_NAME --prev"
    exit 1
}

LEVEL=0

if [ "$1" = "--help" ]; then
    if [ -f $SETTINGS ]; then
        echo "current settings:"
        cat $SETTINGS
    fi
    usage
fi

if [ -f $SETTINGS ]; then
    source $SETTINGS
fi

if [ "$1" = "--next" ]; then
    LEVEL=$((LEVEL + 1))
    if [ "$LEVEL" -gt "$MAX_LEVEL" ]; then
        LEVEL=$MAX_LEVEL
        exit 0
    fi
    read -r TEMP BRIGHTNESS <<< "${LEVELS[$LEVEL]}"
elif [ "$1" = "--prev" ]; then
    LEVEL=$((LEVEL - 1))
    if [ "$LEVEL" -lt 0 ]; then
        LEVEL=0
        exit 0
    fi
    read -r TEMP BRIGHTNESS <<< "${LEVELS[$LEVEL]}"
elif [ "$1" = "--level" ] && [ -n "$2" ]; then
    LEVEL=$2
    if [ "$LEVEL" -lt 0 ]; then
        LEVEL=0
    fi
    if [ "$LEVEL" -gt "$MAX_LEVEL" ]; then
        LEVEL=$MAX_LEVEL
    fi
    read -r TEMP BRIGHTNESS <<< "${LEVELS[$LEVEL]}"
elif [ -n "$1" ] &&[ -n "$2" ]; then
    TEMP=$1
    BRIGHTNESS=$2
    LEVEL=0
else
    usage
fi

if [ "$LEVEL" -eq "$MAX_LEVEL" ]; then
    notify-send "Reached level $LEVEL"
fi

if [ "$LEVEL" -eq "0" ]; then
    notify-send "Reached level $LEVEL"
fi

echo -e "TEMP=$TEMP\nBRIGHTNESS=$BRIGHTNESS\nLEVEL=$LEVEL" > $SETTINGS
echo -e "TEMP=$TEMP\nBRIGHTNESS=$BRIGHTNESS\nLEVEL=$LEVEL"
pkill gammastep
setsid gammastep -m wayland -O "$TEMP" -b "$BRIGHTNESS" &

echo "gm ran with arguments: $@ at $(date)" >> /tmp/gm.log
