#!/bin/sh

type=$(echo -e "packages\noptions\nhome-manager" | dmenu -r -p "search type")
[ -z "$type" ] && exit 0

# if [ "$type" = "home-manager" ]; then
#     xdg-open https://nix-community.github.io/home-manager/options.html
#     exit 1
# fi

query=$(dmenu -p "search" | sed 's/ /+/g')
[ -z "$query" ] && exit 0

case "$type" in
    packages)
        xdg-open "https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=$query"
        ;;
    options)
        xdg-open "https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=$query"
        ;;
    home-manager)
        xdg-open "https://mipmip.github.io/home-manager-option-search/?query=$query"
        ;;
    *) exit 0
        ;;
esac
