#!/usr/bin/env bash

function usage() {
    echo "Usage: $0 <work_duration> <break_duration> <sprints>"
    echo "work_duration: duration of a work sprint in seconds"
    echo "break_duration: duration of a break in seconds"
    echo "sprints: number of work sprints"
    exit 1
}

if [ $# -ne 3 ]; then
    usage
elif [ $1 -lt 1 ] || [ $2 -lt 1 ] || [ $3 -lt 1 ]; then
    echo "All arguments must be positive integers"
    usage
elif [ $1 == "-h" ] || [ $1 == "--help" ]; then
    usage
fi

WORK_DURATION=$(($1 * 60))
BREAK_DURATION=$(($2 * 60))
SPRINTS=$(($3))

function pomodoro_timer() {
    local duration=$1
    local end_time=$((SECONDS + duration))

    while [ $SECONDS -lt $end_time ]; do
        printf "\r%s" "$(display_time $((end_time - SECONDS)))"
        sleep 1
    done

    printf "\r%s" "Time's up!"
    printf "\n"
}

function display_time() {
    local t=$1
    local minutes=$((t / 60))
    local seconds=$((t % 60))
    printf "%02d:%02d" $minutes $seconds
}

function start_pomodoro() {
    echo "Starting Pomodoro..."
    pomodoro_timer $WORK_DURATION
    echo "Pomodoro completed! Take a break."
}

function start_break() {
    echo "Take a short break..."
    pomodoro_timer $BREAK_DURATION
    echo "Break's over! Get back to work."
}

while [ $SPRINTS -gt 0 ]; do
    start_pomodoro
    start_break
    SPRINTS=$((SPRINTS - 1))
done

