#!/bin/sh

VIDEO_FILE="$HOME/media/vids/porelculono/$(date +%Y:%m:%d-%H:%M:%S).mp4"
CLIP_DIR="$HOME/media/vids/porelculono/clips"

# Set the keybind to trigger the clip creation
KEYBIND="ctrl+alt+c"

CLIP_DURATION=60

ffmpeg -y -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -crf 0 "$VIDEO_FILE" &

FFMPEG_PID=$!

trap "kill $FFMPEG_PID" EXIT

while :
do
  xdotool keydown "$KEYBIND"
  xdotool keyup "$KEYBIND"

  TIMESTAMP=$(date +%s)

  START_TIME=$(expr $TIMESTAMP - $CLIP_DURATION)

  ffmpeg -y -ss $START_TIME -i "$VIDEO_FILE" -t $CLIP_DURATION -c copy "$CLIP_DIR/clip_$TIMESTAMP.mp4"

  echo "Clip created: clip_$TIMESTAMP.mp4"
done

