#!/bin/sh

THEMES=$(echo "default modus-operandi modus-vivendi spaceway" | tr ' ' '\n')

CHOICE=$(echo "$THEMES" | dmenu -p "theme: ")

ALACRITTY_DIR="$HOME/.config/alacritty"
DWM_DIR="$HOME/.local/src/dwm"
DMENU_DIR="$HOME/.local/src/dmenu"
NVIM_THEME_FILE="$XDG_CONFIG_HOME/nvim/after/plugin/theme.lua"
X_RESOURCES_FILE_DIR="$XDG_CONFIG_HOME/x11/themes"

WALLPAPER=0

case "$CHOICE" in
    'default')
        NVIM_THEME=default
        WALLPAPER=1
        [ -e $ALACRITTY_DIR/theme.yml ] && rm $ALACRITTY_DIR/theme.yml
        ln -sf $X_RESOURCES_FILE_DIR/modus-vivendi ~/.Xresources
        xrdb ~/.Xresources
        # rm $DWM_DIR/theme.h
        # rm $DMENU_DIR/theme.h
    ;;
    'modus-operandi')
        WALLPAPER=1
        NVIM_THEME=modus-operandi
        ln -sf $X_RESOURCES_FILE_DIR/modus-operandi ~/.Xresources
        xrdb -merge ~/.Xresources
        ln -sf $ALACRITTY_DIR/themes/modus-operandi.yml $ALACRITTY_DIR/theme.yml
    ;;
    'modus-vivendi')
        WALLPAPER=1
        NVIM_THEME=modus-vivendi
        ln -sf $X_RESOURCES_FILE_DIR/modus-vivendi ~/.Xresources
        xrdb -merge ~/.Xresources
        ln -sf $ALACRITTY_DIR/themes/modus-vivendi.yml $ALACRITTY_DIR/theme.yml
    ;;
    'spaceway')
        NVIM_THEME=spaceway
        WALLPAPER=1
        ln -sf $X_RESOURCES_FILE_DIR/spaceway ~/.Xresources
        xrdb -merge ~/.Xresources
        ln -sf $ALACRITTY_DIR/themes/spaceway.yml $ALACRITTY_DIR/theme.yml
    ;;
    'sourcerer')
        NVIM_THEME=sourcerer
        # WALLPAPER=1
        ln -sf $X_RESOURCES_FILE_DIR/sourcerer ~/.Xresources
        xrdb ~/.Xresources
        ln -sf $ALACRITTY_DIR/themes/sourcerer.yml $ALACRITTY_DIR/theme.yml
    ;;
    *) exit
    ;;
esac

if [ "$WALLPAPER" -eq "1" ]; then
    rm $HOME/pix/system-wallpaper
    feh --bg-fill $HOME/pix/wallpapers/themes/$CHOICE.jpg || feh --bg-fill $HOME/pix/wallpapers/themes/$CHOICE.png
    cp $HOME/pix/wallpapers/themes/$CHOICE.jpg $HOME/pix/system-wallpaper || cp $HOME/pix/wallpapers/themes/$CHOICE.png $HOME/pix/system-wallpaper
fi

if [ -n "$NVIM_THEME" ]; then
  echo "vim.cmd('colorscheme $NVIM_THEME')" > $NVIM_THEME_FILE
fi

pkill dwm
