#!/usr/bin/env bash

set -x

NOTES="$PWD/notes"
echo "$NOTES"

cd "$NOTES" || exit 1

echo "running from $PWD"

find . -name "*.md" -exec git add {} +

git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"

git stash

git pull --rebase
git push

git stash pop
