#!/bin/sh

release="/etc/os-release"

if grep -q "nix" "$release"; then
    echo "NixOS detected, updating"
    cd ~/nixos 
    sudo -E nix flake update 
    sudo nixos-rebuild switch --flake . --impure 
    cd -
    exit 0
fi

if grep -q "arch" "$release"; then
    echo "Arch detected, updating"
    sudo pacman -Syu
    paru
    exit 0
fi
