#!/bin/sh

TARGET_USER="$1"
DOTDIR="$2"
USER_HOME=/home/$TARGET_USER

mkdir -p "$USER_HOME/.config"

which zsh > /dev/null 2>&1

if [ $? -eq 1 ]; then
    sudo pacman --noconfirm --needed -S zsh
fi

if [ "$(grep "^$TARGET_USER" /etc/passwd | cut -d: -f7)" != "/usr/bin/zsh" ]; then
    sed -i '/sergio/s#/bin/bash#/usr/bin/zsh#' /etc/passwd
fi

if [ -h $USER_HOME/.config/zsh ]; then
    rm $USER_HOME/.config/zsh
fi

if [ -h $USER_HOME/.config/shell ]; then
    rm $USER_HOME/.config/shell
fi

ln -sfv $DOTDIR/.config/zsh $USER_HOME/.config/zsh
ln -sfv $DOTDIR/.config/shell $USER_HOME/.config/shell
cp -dfv $DOTDIR/.zprofile $USER_HOME/.zprofile
cp -dfv $DOTDIR/.zprofile $USER_HOME/.profile
