#!/bin/sh

[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"
[ -f "$XDG_CONFIG_HOME/x11/font" ] && xrdb -merge "$XDG_CONFIG_HOME/x11/font"
# [ -f "$XDG_CONFIG_HOME/x11/cursor" ] && xrdb -merge "$XDG_CONFIG_HOME/x11/cursor"

[ -f "$HOME/.local/x_autostart.sh" ] && $HOME/.local/x_autostart.sh

# while true; do
#     dwm >/dev/null 2>&1
# done

nm-applet --indicator &
dwmblocks &
dunst &
sxhkd &
unclutter -idle 5 &

export SYSTEM_MENU=dmenu

while true; do
    # Log stderror to a file
    dwm 2> /tmp/dwm.log
    # No error logging
    # dwm >/dev/null 2>&1
done

exec dwm
