require("sergio.settings")
require("sergio.keybinds")
require("sergio.writting")
require("sergio.lazy")
require("sergio.colors")
require("sergio.gtd")
require("sergio.sudo")
require("sergio.copilot")
