# [colors.bright]
# black = "#709080"
# blue = "#94BFF3"
# cyan = "#93E0E3"
# green = "#A8FF60"
# magenta = "#EC93D3"
# red = "#DCA3A3"
# white = "#FFFFFF"
# yellow = "#FFEF60"

# [colors.normal]
# black = "#3F3F3F"
# blue = "#6D85BA"
# cyan = "#94BFF3"
# green = "#7F9F7F"
# magenta = "#DFAF8F"
# red = "#CC9393"
# white = "#DCDCCC"
# yellow = "#F0DFAF"

[colors.primary]
background = "#282c34"
foreground = "#bcbfc4"
