[colors.cursor]
text = "#CDCDCD"

[colors.normal]
black = "#191919"
blue = "#7D8FA3"
cyan = "#009999"
green = "#a1bf78"
magenta = "#aa759f"
red = "#CC6666"
white = "#acadb1"
yellow = "#E5C078"

[colors.primary]
background = "#000000"
foreground = "#CDCDCD"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
