[colors]
author = "senpai-10"
name = "vscode (dark)"

[colors.cursor]
cursor = "#cccccc"
text = "#1d1f21"

[colors.normal]
black = "#000000"
blue = "#569CD6"
cyan = "#11a8cd"
green = "#6A9955"
magenta = "#646695"
red = "#F44747"
white = "#e5e5e5"
yellow = "#DCDCAA"

[colors.primary]
background = "#1E1E1E"
foreground = "#D4D4D4"
