[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2b3339"
foreground = "#d3c6aa"

[schemes.everforest_dark_emacs.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_emacs.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_emacs.primary]
background = "#2b3339"
foreground = "#d3c6aa"

[schemes.everforest_dark_hard.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_hard.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_hard.primary]
background = "#272E33"
foreground = "#d3c6aa"

[schemes.everforest_dark_medium.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_medium.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_medium.primary]
background = "#2f383e"
foreground = "#d3c6aa"

[schemes.everforest_dark_soft.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_soft.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[schemes.everforest_dark_soft.primary]
background = "#323d43"
foreground = "#d3c6aa"

[schemes.everforest_light_hard.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_hard.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_hard.primary]
background = "#fff9e8"
foreground = "#5c6a72"

[schemes.everforest_light_medium.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_medium.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_medium.primary]
background = "#fdf6e3"
foreground = "#5c6a72"

[schemes.everforest_light_soft.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_soft.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[schemes.everforest_light_soft.primary]
background = "#f8f0dc"
foreground = "#5c6a72"
