[colors.bright]
black = "#126367"
blue = "#ffffff"
cyan = "#8cde94"
green = "#ffaa00"
magenta = "#c1d1e3"
red = "#ff0000"
white = "#ffffff"
yellow = "#7ad0c6"

[colors.normal]
black = "#062329"
blue = "#ffffff"
cyan = "#8cde94"
green = "#44b340"
magenta = "#c1d1e3"
red = "#ffffff"
white = "#c1d1e3"
yellow = "#2ec09c"

[colors.primary]
background = "#062329"
foreground = "#d1b897"
