[colors.bright]
blue = "#8787AF"
cyan = "#87ceeb"
green = "#719611"

[colors.cursor]
cursor = "#87AFD7"
text = "#CDCDCD"

[colors.normal]
black = "#191919"
blue = "#6688aa"
cyan = "#528b8b"
green = "#87875f"
magenta = "#8787AF"
red = "#aa4450"
white = "#acadb1"
yellow = "#cc8800"

[colors.primary]
background = "#171717"
foreground = "#CDCDCD"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
