bg_default: &bg_default {stack: [{background: {color: 92a58bff}} ]}
fg_default: &fg_default {stack: [{foreground: {color: 555555ff}} ]}
#, {foreground: {color: 555555ff}}
bar:
  height: 20
  location: top
  font: monospace:pixelsize=14
  spacing: 0
  margin: 2
  layer: bottom
  foreground: ccccccff
  background: 222222dd

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: 1 }}
              conditions:
                id == 1: {string: {text: 1 }}
                id == 2: {string: {text: 2 }}
                id == 3: {string: {text: 3 }}
                id == 4: {string: {text: 4 }}
                id == 5: {string: {text: 5 }}
                id == 6: {string: {text: 6 }}
                id == 7: {string: {text: 7 }}
                id == 8: {string: {text: 8 }}
                id == 9: {string: {text: 9 }}
                id == 10: {string: {text: "scratchpad" }}
                id == 11: {string: {text: "work" }}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied && id < 10:
                map:
                  <<: *river_base
              state == invisible && occupied:
                map:
                  <<: *river_base
                  # deco: {underline: {size: 3, color: ea6962ff}}
  right:
    - clock:
        content:
          - string: {text: "{time}"}

