#!/bin/bash

# script to remove unused images in my notes

notesdir="$HOME/notes"

for img in $(ls $notesdir/.img); do
    present=$(rg "$img" $notesdir/* | wc -l )
    if [ $present == 0 ]; then
        echo "removing $img"
        rm -f notesdir/.img/$img
    fi
done
