#!/bin/sh

[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"
[ -f "$XDG_CONFIG_HOME/X11/font" ] && xrdb -merge "$XDG_CONFIG_HOME/x11/font"

feh --no-fehbg --bg-fill ~/pix/wal/default &
# picom &
nm-applet --indicator &
dwmblocks &
dunst &
sxhkd &
unclutter -idle 5 &
# kmonad $HOME/.config/kmonad/simple.kbd &
# xautolock -time 10 -locker slock &

# the following commands are equivalent to the command
# source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

gnome-keyring-daemon --start --components=secrets

while true; do
    dbus-launch --exit-with-session dwm 2> /tmp/dwm.log
    if [ ! -e "/tmp/hotreloading" ]; then
        break
    fi
done

# exec dwm 2> /tmp/dwm.log
# exec stumpwm 2> /tmp/stumpwm.log
