#!/bin/bash

sudo pacman -S --needed \
    alacritty \
    base \
    base-devel \
    btrfs-progs \
    cmake \
    direnv \
    discord \
    dunst \
    efibootmgr \
    firefox \
    fzf \
    git \
    gst-plugin-pipewire \
    intel-ucode \
    libnotify \
    libpulse \
    linux \
    linux-firmware \
    neofetch \
    networkmanager \
    ninja \
    openssh \
    pavucontrol \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulse \
    pulsemixer \
    ripgrep \
    rustup \
    scrot \
    sxhkd \
    ttf-liberation-mono-nerd \
    unzip \
    vim \
    wireplumber \
    xdg-desktop-portal-gtk \
    xorg-server \
    xorg-xinit \
    zsh \

sudo pacman -S --needed \
    nvidia \
    steam \
    lutris \

# paru

if ! [[ $(which paru) ]]; then
    sudo pacman -S --needed base-devel
    mkdir -p ~/.local/src
    git clone https://aur.archlinux.org/paru.git ~/.local/src
    cd ~/.local/src/paru
    makepkg -si
fi
