#!/usr/bin/env bash

cd ~/dl
mkdir pdf zip iso 2> /dev/null

while [[ true ]]; do
    mv -v *.pdf pdf/ 2> /dev/null
    mv -v *.zip zip/ 2> /dev/null
    mv -v *.iso /mnt/ssd/vm/iso/ 2> /dev/null
    sleep 5
done
