#!/bin/sh
CHOICE=$(echo -e "laptop-only\nlaptop-external-only\nexternal\nracing\ndual\narandr" | dmenu -p monitor)

# case "$CHOICE" in
# 	laptop) xrandr --output eDP --primary --mode 1920x1080 --output HDMI-A-0 --off &; sed -i 's/size: 12/size: 9'/ ~/.config/alacritty/alacritty.yml & ;;
# 	external) bash ./monitormenuscripts/external & ;;
# 	dual) xrandr --output HDMI-A-0 --primary --mode 1920x1080 --output eDP --mode 1920x1080 --left-of HDMI-A-0 & ;;
# 	arandr) arandr & disown;;
# esac

case "$CHOICE" in
    'laptop-only')
 		xrandr --output eDP --primary --mode 1920x1080 --output HDMI-A-0 --off
        ln -sf $HOME/.config/alacritty/fonts/laptop.yml $HOME/.config/alacritty/font.yml
    ;;
    'laptop-external-only')
        xrandr --output eDP --off || wlr-randr --output eDP --off
        ln -sf $HOME/.config/alacritty/fonts/laptop-219.yml $HOME/.config/alacritty/font.yml
    ;;
    'external')
		xrandr --output HDMI-A-0 --primary --mode 1920x1080 --output eDP --off
		sed -i 's/size: 9/size: 12'/ ~/.config/alacritty/alacritty.yml
    ;;
    'racing')
		xrandr --output DP-4 --mode 2560x1080 --right-of DVI-D-0
    ;;
    '[MainLeft]')
        xrandr --output LVDS1 --mode 1366x768 --left-of VGA1 --primary
        xrandr --output VGA1 --mode 1920x1080
    ;;
    '[MainRight]')
        xrandr --output LVDS1 --mode 1366x768 --right-of VGA1 --primary
        xrandr --output VGA1 --mode 1920x1080
    ;;
    '[ARandR]')
        arandr & disown
    ;;
    # *'On'*)
    #     xset dpms force on
    # ;;
    # *'Off'*)
    #     xset dpms force off
    # ;;
esac
