#!/bin/bash

CHOICE=$(echo -e "es\nus\nus-int\ndvorak" | dmenu -p layout)

case "$CHOICE" in
	es) setxkbmap es -option ctrl:nocaps & ;;
	us) setxkbmap us -option caps:escape & ;;
	us-int) setxkbmap -layout us -variant intl -option caps:escape & ;;
	dvorak) setxkbmap es -option caps:escape & ;;
esac
