#!/bin/sh

brightness=$(echo "" | dmenu -p "Select a brightness factor")
if [ -z "$brightness" ]; then
    exit 1
fi

case $XDG_SESSION_TYPE in
    wayland)
        echo "This script is not supported on Wayland"
        notify-send "This script is not supported on Wayland"
        ;;
    xorg|*)
        xrandr | grep " connected" | cut -d " " -f 1 | xargs -I _ xrandr --output _ --brightness "$brightness"
        exit 0
        ;;
esac

