#!/bin/sh

# CURRENT_Q is an enviroment variable that should be setted up to be the current Q

# echo $CURRENT_Q

# bemenu_options=$(cat $HOME/.local/scripts/bemenu2)

asignatura=$(ls "$UNI"/"$CURRENT_Q" | dmenu -i -p "asignatura") || exit

file=$(find $UNI/$CURRENT_Q/$asignatura -type f -name "*.pdf" | \
# file=$(find $UNI/$CURRENT_Q/$asignatura -type f | \
    sed "s~${UNI}/${CURRENT_Q}/${asignatura}~~g" | dmenu -i -p "open" -l 30)

echo $file

if [ -n "$file" ]; then
    xdg-open "$UNI/$CURRENT_Q/$asignatura/$file"
fi

