#!/bin/bash

# script to take a screenshots of a section save it at screenshots dir and pipe the image into the clipboard
if [ "$1" == "--name-prompt" ]; then
    filename=$(dmenu -p "[normal sc] name:")
else
    filename=$(date +%Y%m%d%H%M%S)
fi

maim --select | tee $HOME/pix/screenshots/$filename.png | xclip -selection clipboard -t image/png

# maim --select | tee $HOME/pix/screenshots/$(date +%Y%m%d%H%M%S).png | xclip -selection clipboard -t image/png
