#!/bin/sh

query=$(dmenu -p "search" | sed 's/ /+/g')

if [ -z "$query" ]; then
    exit 0
fi

firefox "https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=$query"
