#!/usr/bin/env bash

if [ "$1" == "--type" ]; then
    passmenu -l 30 --type
else
    passmenu -l 30 > /tmp/passtmp
fi

if [ $? -eq 0 ]; then
    if [ "$1" == "--type" ]; then
        notify-send "pass" "Content typed in the active window"
    else
        notify-send "pass" "$(cat /tmp/passtmp)"
    fi
fi
