#!/bin/bash

UNI=$UNI_PATH
NOTES="$HOME/notes"

function push () {
    cd $1
    echo "Commiting $1 folder, write a commit message:"
    git status
    read MSG
    git add .
    git commit -m "$MSG"
    git push
}

function pushall () {
    push $UNI
    push $NOTES
}

function pull () {
    echo "Pulling $1 folder"
    cd $1
    git pull
}

function pullall () {
    pull $UNI
    pull $NOTES
}

if [ "$1" == "pull" ] || [ "$1" == "push" ]; then
    $1 $2
else
    OPTIONS="pushall\npullall"
    CHOICE=$(echo -e $OPTIONS | fzf)
    case "$CHOICE" in
        pullall) pullall ;;
        pushall) pushall ;;
        *) exit ;;
    esac
fi
