#!/bin/bash

destdir='$HOME/pictures/screenshots/%Y%m%d%H%M%S.png'
echo $destdir

# scrot -s '/home/sergio/pictures/screenshots/%Y%m%d%H%M%S.png' -e 'xclip -selection clipboard -target image/png -i $f'
