#!/usr/bin/env bash

mkdir -p /tmp/0x0

input=$1
base="${input%.*}"

name=$(uuidgen | cut -d'-' -f1)

cp $input /tmp/0x0/$name
zip -r /tmp/0x0/$name.zip /tmp/0x0/$name
zipcloak /tmp/0x0/$name.zip

pass=$(tr -dc 'A-Za-z0-9!@#$%^&*()_+{}[]' </dev/urandom | head -c 32)

echo $name
curl -F"file=@/tmp/0x0/$name.zip" 0x0.st
