#!/bin/bash

SESSION_NAME=zeos
PROJECT_PATH='/tmp/zeos'

# function start_vm

if [ "$1" == "off" ]; then
    fusermount3 -zu /tmp/zeos
    rmdir /tmp/zeos
    virsh shutdown sistemes || exit
    echo "All umounted properly"
    exit
fi

! [ -d "/tmp/zeos" ] && mkdir /tmp/zeos

status=$(virsh list | grep sistemes | wc -l)
# echo "The VM is [0] off [1] on"
# echo "$status"

if [ "$status" -eq "0" ]; then
    virsh start sistemes
    zenity --info --text "Waiting for the VM to boot" &
    echo "Waiting for the VM to boot..."
    while true; do
        ssh -q alumne@sistemes exit
        if [ $? -eq 0 ]; then
            killall zenity
            break
        fi
        sleep 1
done
fi

sshfs alumne@sistemes:/home/alumne /tmp/zeos
cd /tmp/zeos/zeos
setsid emacsclient -c . &
ssh alumne@sistemes
