#!/bin/bash

SESSION_NAME=default

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]
then
    tmux new-session -s $SESSION_NAME -d
fi

if [ -z $TMUX ]; then
    tmux attach -t $SESSION_NAME
else
    tmux switch-client -t $SESSION_NAME
fi

