#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/uni/"$CURRENT_Q" ~/personal ~/.local/src ~/.dotfiles/.local -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -e "$selected/.tmux" ]]; then
    sh $selected/.tmux
    exit
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $selected_name
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $selected_name
fi
