#!/bin/sh

SESSION_NAME=config
PROJECT_PATH="$HOME/nixos"

tmux has-session -t $SESSION_NAME 2>/dev/null
if [ $? != 0 ]          # si no hay sesion se crea
then
    tmux new-session -s $SESSION_NAME -d
    tmux send-keys -t $SESSION_NAME "cd $HOME/nixos" C-m
    tmux rename-window nix -t $SESSION_NAME C-m
    tmux send-keys -t $SESSION_NAME "nvim ." C-m
    tmux new-window -n dot -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:2 "cd $HOME/.dotfiles" C-m
    tmux send-keys -t $SESSION_NAME:2 "nvim . " C-m
    tmux new-window -n shell -t $SESSION_NAME
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
