#!/bin/bash

sdx="$UNI/3q2/sdx"

reading_session() {
    cd "$sdx/reading"
    reading=$(ls -d */ | fzf)
    PROJECT_PATH="$sdx/reading/$reading"
    cd $PROJECT_PATH
    zathura *.pdf &
    tmux new-session -s $SESSION_NAME -d
    tmux send-keys -t $SESSION_NAME "nvim *.tex" C-m
}

seminar_session() {
    cd "$sdx/github"
    seminar=$(ls -d */ | fzf)
    PROJECT_PATH="$sdx/github/$seminar/src"
    cd $PROJECT_PATH
    firefox ../*.pdf &
    tmux new-session -s $SESSION_NAME -d
    tmux send-keys -t $SESSION_NAME "nvim ." C-m
    tmux new-window -n zsh -t $SESSION_NAME
    # tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
    # tmux split-window -v -t $SESSION_NAME
    tmux split-window -t $SESSION_NAME:2
    tmux send-keys -t $SESSION_NAME:2.1 "clear" C-m
}

SESSION_NAME=$(echo -e "sdx-reading\nsdx-seminar" | fzf)
tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]          # si no hay sesion se crea
then
    case "$SESSION_NAME" in
        sdx-reading) reading_session ;;
        sdx-seminar) seminar_session ;;
        *) exit ;;
    esac
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
