#!/bin/sh

SESSION_NAME="notes"
PROJECT_PATH="$HOME/notes"

cd "$PROJECT_PATH" || exit

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]          # si no hay sesion se crea
then
    tmux new-session -s $SESSION_NAME -d -c "$PROJECT_PATH"
    tmux send-keys -t $SESSION_NAME "nvim index.md" C-m
    tmux new-window -n tfg -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME "cd uni/tfg/memoria" C-m
    tmux send-keys -t $SESSION_NAME "nvim memoria.tex" C-m
    tmux send-keys -t $SESSION_NAME " O" C-m
    tmux send-keys -t $SESSION_NAME " m" C-m
    tmux new-window -n sh -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME "cd uni/tfg/memoria" C-m
    tmux send-keys -t $SESSION_NAME "clear" C-m
    # tmux new-window -n git -t $SESSION_NAME
    # tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH" C-m
    # tmux send-keys -t $SESSION_NAME:2 "lazygit" C-m
    # tmux send-keys -t $SESSION_NAME:2 "$EDITOR todo.md" C-m
    # tmux send-keys -t $SESSION_NAME:3 "cd $PROJECT_PATH" C-m
    # tmux send-keys -t $SESSION_NAME:3 "$EDITOR uni.md" C-m
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
