#!/bin/sh

SESSION_NAME=pti
PROJECT_PATH="$HOME/code/car-tracking-fullstack"

tmux has-session -t $SESSION_NAME 2>/dev/null
if [ $? != 0 ]          # si no hay sesion se crea
then
    tmux new-session -s $SESSION_NAME -d
    tmux send-keys -t $SESSION_NAME "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME "nvim ." C-m
    tmux new-window -n term -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
    tmux new-window -n bacon -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:3 "cd $PROJECT_PATH" C-m
    tmux send-keys -t $SESSION_NAME:3 "bacon" C-m
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
