#!/bin/sh

SESSION_NAME=zeos
PROJECT_PATH="$HOME/code/zeos"

start_vm () {
  if [ "$1" == "--close" ]; then
    fusermount3 -zu /tmp/soa
    rmdir /tmp/soa
    virsh shutdown sistemes || exit
    echo "All umounted properly"
    tmux kill-session -t zeos
    exit
  fi

  status=$(virsh list | grep sistemes | wc -l)

  if [ "$status" -eq "0" ]; then
    virsh net-start default
    virsh start sistemes
    echo "Waiting for the VM to boot..."
    echo "ZeOS is the skeleton of a simple Operating System based on a Linux 2.4 kernel and developed for the intel 80386 architecture." | cowsay -f daemon
    while true; do
      ssh -q alumne@sistemes exit
      if [ $? -eq 0 ]; then
        break
      fi
      sleep 1
    done
  fi
  sshfs sistemes:zeos $PROJECT_PATH
}



tmux has-session -t $SESSION_NAME 2>/dev/null
if [ $? != 0 ]          # si no hay sesion se crea
then
    tmux new-session -s $SESSION_NAME -d
    # tmux setenv ASIG=soa
    # tmux send-keys -t $SESSION_NAME "export ASIG=soa" C-m
    tmux send-keys -t $SESSION_NAME "cd $PROJECT_PATH/project" C-m
    tmux send-keys -t $SESSION_NAME "nvim ." C-m
    tmux new-window -n shell -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:2 "cd $PROJECT_PATH/project" C-m
    tmux send-keys -t $SESSION_NAME:2 "nix develop" C-m
    tmux send-keys -t $SESSION_NAME:2 "zsh" C-m
    tmux send-keys -t $SESSION_NAME:2 "clear" C-m
fi

if [ -z $TMUX ]; then   # si estamos fuera de tmux hacemos attach
    tmux attach -t $SESSION_NAME:1
else                    # si estamos dentro solo cambiamos el cliente
    tmux switch-client -t $SESSION_NAME:1
fi
