#!/bin/sh

which acpi > /dev/null 2>&1

if [ $? -eq 1 ]; then
    echo "acpi not found"
    exit 1
fi

info=$(acpi | cut -d: -f2)
status=$(echo $info | cut -d, -f1)
capacity=$(echo $info | cut -d, -f2)
# capacity=${capacity%?}

echo $status $capacity
