#!/bin/bash

status=$(bat-asus-battery status)
capacity=$(bat-asus-battery capacity)

# make it equal to the max battery level of your device
maxbatterylevel=79

gap=$((capacity/10))

[[ $status == "Charging" ]] && gap=charging
[[ $capacity -eq $maxbatterylevel ]] && gap=10

case "$gap" in
    0|1|2) icon=" " ;;
    3|4) icon=" " ;;
    5|6) icon=" " ;;
    7|8) icon=" " ;;
    9|10) icon=" " ;;
    charging) icon="" ;;
    *) 
    ;;
esac

echo "$icon $capacity% $status"
